### ISSUE TITLE
Version bump for gazebo path patch

### ISSUE THREAD

**Issue by cottsay** [turtlebot/turtlebot_create_desktop#12]
I'm not sure what is happening in Ubuntu that makes https://github.com/turtlebot/turtlebot_create_desktop/commit/99f81f10afdeb371460937db3abd5952a3eafcaf work at all, but this patch completely breaks Fedora (and others, I'm sure). Both pkgconfig and CMake report that the include path does NOT include the "gazebo" at the end, and so it is needed in the source files.

Does it work either way in Ubuntu? If so, please revert the patch.

**Comment by cottsay** [comment]
Whoops! Looks like I spoke too soon. This is the OPPOSITE problem as I described: it looks like Fedora needs this patch to be present to compile. Completely my fault.

Any chance we can get a version bump?

**Comment by jihoonl** [comment]
Sure. I am testing now :)

**Comment by cottsay** [comment]
Thanks!
