### ISSUE TITLE
create_gazebo_plugins failure to compile with gazebo7

### ISSUE THREAD

**Issue by tfoote** [turtlebot/turtlebot_create_desktop#18]
Gazebo 7 uses c++11 headers which means that this doesn't compile.  Either this needs to add c++11 flags to the objects using those headers or it should be ticketed upstream for gazebo_ros to export the flags. Though even if they are exported above, we'll need to use them in this package. 

There's a related discussion at: https://github.com/ros/resource_retriever/pull/7 which was resolved by
https://github.com/ros-visualization/rviz/commit/faf97becbbb51e08227e00557d171a9c60a81c79

http://build.ros.org:8080/view/Queue/job/Kbin_uX32__create_gazebo_plugins__ubuntu_xenial_i386__binary/1/console

```
15:27:00 [ 50%] Building CXX object CMakeFiles/gazebo_ros_create.dir/src/gazebo_ros_create.cpp.o
15:27:00 /usr/lib/ccache/i686-linux-gnu-g++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"create_gazebo_plugins\" -Dgazebo_ros_create_EXPORTS -I/tmp/binarydeb/ros-kinetic-create-gazebo-plugins-2.3.1/include -I/opt/ros/kinetic/include -I/usr/include/gazebo-7 -I/usr/include/sdformat-4.0 -I/usr/include/ignition/math2  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC   -o CMakeFiles/gazebo_ros_create.dir/src/gazebo_ros_create.cpp.o -c /tmp/binarydeb/ros-kinetic-create-gazebo-plugins-2.3.1/src/gazebo_ros_create.cpp
15:27:07 In file included from /usr/include/c++/5/random:35:0,
15:27:07                  from /usr/include/ignition/math2/ignition/math/Rand.hh:20,
15:27:07                  from /usr/include/ignition/math2/ignition/math.hh:18,
15:27:07                  from /usr/include/sdformat-4.0/sdf/Param.hh:34,
15:27:07                  from /usr/include/sdformat-4.0/sdf/Element.hh:24,
15:27:07                  from /usr/include/sdformat-4.0/sdf/sdf.hh:5,
15:27:07                  from /usr/include/gazebo-7/gazebo/sensors/SensorManager.hh:26,
15:27:07                  from /tmp/binarydeb/ros-kinetic-create-gazebo-plugins-2.3.1/src/gazebo_ros_create.cpp:1:
15:27:07 /usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
15:27:07  #error This file requires compiler and library support \
15:27:07   ^
15:27:10 In file included from /usr/include/sdformat-4.0/sdf/sdf.hh:3:0,
15:27:10                  from /usr/include/gazebo-7/gazebo/sensors/SensorManager.hh:26,
15:27:10                  from /tmp/binarydeb/ros-kinetic-create-gazebo-plugins-2.3.1/src/gazebo_ros_create.cpp:1:
```

**Comment by stonier** [comment]
That is a small essay over there for the resource_retriever. 

Are there any _users_ (in the compiling sense) of this package?

If not then I'd just set the c++11 flags so as to get this rolled out.  The only downside would be having to touch this again when gcc has moved on farther to not need them or need different flags.   

Gazebo ROS can handle it as it wishes in its own time then.

**Comment by tfoote** [comment]
I agree, this package only compiles the plugin so it doesn't need to export it along anymore. Unfortunately that will mean a fork for kinetic, but it won't take too much time.
