### ISSUE TITLE
Fix ABI/API breakages coming with Gazebo 2.0

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_create_desktop#7]
Gazebo 2.0 breaks API and ABI compatibility at various points. So far I spotted the following:
- [x] new paths for gazebo header includes, e.g. `common/common.hh` -> `gazebo/common/common.hh`
- [ ] collision/contact detection is done differently

**Comment by bit-pirate** [comment]
Gazebo 2.0 was accidentally released into ROS Hydro. They reverted that change now - default for Hydro will remain 1.9. Hence, there are no breakages we have to fix.

Once we want to use the new Gazebo version, we should create a separate branch.

**Comment by cottsay** [comment]
Please re-open this bug.

Fedora's Gazebo is using the new ABI and the `ContactManager` changes are breaking builds. It looks like the change would be pretty easy for someone who knows the code...

**Comment by jihoonl** [comment]
What is `ContactManager`?

**Comment by cottsay** [comment]
Thanks for re-opening.

`ContactManager` is the suggested method for replacing `ConnectContact`.

See https://bitbucket.org/osrf/gazebo/issue/879/gazebo-collision-connectcontact-removed

**Comment by bit-pirate** [comment]
> Fedora's Gazebo is using the new ABI

There must be something wrong with the Gazebo release on Fedora then. During the life-time of a ROS release no breaking ABI/API change is allowed. That also means for us, that we can't change the API as well. Otherwise we will break the API for the current users.

Please check the Gazebo version on your system. I remember there are ways to install both the old (1.9.X) and new (2.X.X) version of Gazebo.

**Comment by cottsay** [comment]
ROS is not currently packaged for Fedora (something I'm working on). The version of Gazebo in Fedora will be 2.2.1 (when it is added [1]).

You're assuming that you must support one OR the other. Even if (1.9.X) is the current ABI in Ubuntu, that doesn't mean you can't SUPPORT newer API/ABI. You'll have to add support for (2.X.X) eventually, anyway, and the changes to add (2.X.X) compatibility won't break (1.9.X).

The `ContactManager` has been in Gazebo for a long time, and switching to it will not break your compatibility. It is present in (1.9.X).

`ConnectContact` has been deprecated for well over a year [2] in lieu of `ContactManager`, which was added over 2 years ago. It is deprecated in (1.9.X) and was deprecated even before that.

Thanks,

--scott

[1] https://bugzilla.redhat.com/show_bug.cgi?id=825409
[2] https://bitbucket.org/osrf/gazebo/commits/3fa7fe9b01000a2759e35ea241f7ee34e56a5209

**Comment by bit-pirate** [comment]
If you prepare a Hydro release for Fedora, then I recommend to release it with Gazebo 1.9.X in order to stay in sync with the Ubuntu release.

You are right, that we have to do the upgrade at some point any way, but I would prefer to tackle the whole set of changes when we move to Indigo.

Currently there are not many people working on and submitting patches to the turtlebot and kobuki packages - you are an exception. Also, I won't have time to tackle this any time soon. Hence, I suggest to stay with the old Gazebo version and upgrade later.

**Comment by cottsay** [comment]
I understand.

I'll try to take a look at upgrading this myself, but I'm not sure if I have the time either. I'm fairly certain that the contact fix will bring the package up to a functioning state for (2.2.X).

So far this is the only package that has problems compiling against Gazebo (2.2.X), and I've compiled almost 800 of the 1100 packages in hydro. I anticipate that the r2 will have the same issue. It would be a shame if these were the only two packages that won't work.

**Comment by bit-pirate** [comment]
If I find time, then I'll take a look at it.

Btw, did you discuss releasing Gazebo 2.2.X for Hydro on Fedora on the ros-release list? This seems to me like a potentially big issue - remembering to uproar it caused when being released for Ubuntu.

**Comment by cottsay** [comment]
Fedora doesn't officially have Gazebo right now. The package will likely be added to the official repos in the near future, but it is not there yet. With all of the compile problems in ROS on Fedora at the moment, I'm pretty sure that very few people have gotten this far.

Fedora is and has always been much closer to the bleeding edge of software than Ubuntu has. It would not be favourable to add anything but the newest version of Gazebo to the repositories.

**Comment by stonier** [comment]
It's now indigo and we have to hit this issue...compilation error is as below:

```
/opt/turtlebot/src/turtlebot_create_desktop/create_gazebo_plugins/src/gazebo_ros_create.cpp: In member function ‘virtual void gazebo::GazeboRosCreate::Load(gazebo::physics::ModelPtr, sdf::ElementPtr)’:
/opt/turtlebot/src/turtlebot_create_desktop/create_gazebo_plugins/src/gazebo_ros_create.cpp:106:38: warning: ‘void gazebo::physics::Collision::SetContactsEnabled(bool)’ is deprecated (declared at /usr/include/gazebo-2.2/gazebo/physics/Collision.hh:123) [-Wdeprecated-declarations]
   base_geom_->SetContactsEnabled(true);
                                      ^
/opt/turtlebot/src/turtlebot_create_desktop/create_gazebo_plugins/src/gazebo_ros_create.cpp:107:32: error: ‘class gazebo::physics::Collision’ has no member named ‘ConnectContact’
   contact_event_ = base_geom_->ConnectContact(boost::bind(&GazeboRosCreate::OnContact, this, _1, _2));
                                ^
make[2]: *** [turtlebot_create_desktop/create_gazebo_plugins/CMakeFiles/gazebo_ros_create.dir/src/gazebo_ros_create.cpp.o] Error 1
make[1]: *** [turtlebot_create_desktop/create_gazebo_plugins/CMakeFiles/gazebo_ros_create.dir/all] Error 2
```

**Comment by bchretien** [comment]
:+1: Same issue on Arch. I was trying to find packages that would clash with Gazebo 2/3 to find the maximum Gazebo version to use, and I guess I did. What @cottsay said about Fedora is even truer for Arch Linux (hence my tests with Gazebo 3.0), so I agree with everything he said ;-)

**Comment by trainman419** [comment]
Is this fixed now that #16 is merged?

**Comment by cottsay** [comment]
I see no compile errors on Fedora with Gazebo 3.1.0. Thanks for fixing this!

**Comment by stonier** [comment]
Closing this as it appears to be in working order...reopen if necessary.
