### ISSUE TITLE
boost::shared_*_cast are deprecated, removed in boost 1.53

### ISSUE THREAD

**Issue by bchretien** [turtlebot/turtlebot_create_desktop#9]
Compilation currently fails on Arch Linux (and any distribution using boost >= 1.53).

cf. https://bitbucket.org/osrf/gazebo/issue/581/boost-shared_-_cast-are-deprecated-removed

**Comment by stonier** [comment]
Could use a pull request ;)

Otherwise might be a little while before we get around to tackling this.

**Comment by bchretien** [comment]
I was just trying to package it for Arch Linux, even though I do not have any need for this. I don't have much time on my hands either, but I figured that the least I could do was report the issue ;-)

**Comment by stonier** [comment]
That's certainly useful and thanks for the link.

**Comment by bit-pirate** [comment]
Same issue here: https://github.com/yujinrobot/kobuki_desktop/issues/25

**Comment by jihoonl** [comment]
#10 fixes.
